import "./globals.css";
import AppRootShell from "./AppRootShell";

// Remove the metadata export
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRootShell>{children}</AppRootShell>
      </body>
    </html>
  );
}
