import "./globals.css";

// Remove the metadata export
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className="antialiased bg-sh-background text-sh-foreground flex flex-col min-h-screen w-full"
      style={{
        ['--font-geist-sans' as string]: '"Trebuchet MS", "Avenir Next", "Segoe UI", sans-serif',
        ['--font-geist-mono' as string]: '"SFMono-Regular", "Consolas", monospace',
        ['--font-story' as string]: 'Georgia, "Lora", "Times New Roman", serif',
      }}
    >
      {children}
    </div>
  );
}
